#!/bin/bash

if [ $# != 1 ]; then
  echo "Missing RPi IP"
  exit 1
fi

ip=$1

ssh pi@$ip "grep jessie /etc/os-release" &>/dev/null
if  [ $? != 0 ]; then
  echo "You're not a Raspberry Pi"
  exit 2
fi

ssh pi@$ip "if [ ! -e /home/pi/ff-voc ]; then mkdir /home/pi/ff-voc/; fi"
rsync -avz . pi@$ip:/home/pi/ff-voc/
